from __future__ import annotations

import base64
import logging
import os
import re
import shlex
import socket
from typing import Callable

from . import AZURE_USERNAME
from .profile import validate_server_secret

log = logging.getLogger(__name__)

BASE64_LINE_LENGTH = 768
CLIENT_VERSION = 5
_SAFE_VALUE = re.compile(r"^[A-Za-z0-9._/:@+-]+$")


def _value(value: str, what: str) -> str:
    if not _SAFE_VALUE.match(value):
        raise ValueError(f"{what} contains characters not allowed in an OpenVPN config: {value!r}")
    return value


def static_key(server_secret: str) -> str:
    secret = validate_server_secret(server_secret)
    lines = [secret[i : i + 32] for i in range(0, len(secret), 32)]
    return "\n".join(["-----BEGIN OpenVPN Static key V1-----", *lines, "-----END OpenVPN Static key V1-----"])


def render_config(
    *,
    gateways: list[str],
    port: int,
    server_secret: str,
    ca_path: str,
    management_socket: str,
    helper_command: list[str] | None,
    dev: str = "tun",
    verify_name: str | None = None,
    verb: int = 3,
) -> str:
    lines = [
        "# Generated by nm-openp2s for NetworkManager. Rewritten on every connect.",
        "client",
        f"dev {_value(dev, 'dev')}",
        "proto tcp-client",
        *(f"remote {_value(g, 'gateway')} {int(port)}" for g in gateways),
        "nobind",
        "resolv-retry infinite",
        "remote-cert-tls server",
    ]
    if verify_name:
        lines.append(f"verify-x509-name {_value(verify_name, 'verify-name')} name")
    lines += [
        "cipher AES-256-GCM",
        "data-ciphers AES-256-GCM",
        "data-ciphers-fallback AES-256-GCM",
        "auth SHA256",
        "reneg-sec 0",
        "auth-nocache",
        f"ca {_value(ca_path, 'CA path')}",
        "auth-user-pass",
        "auth-retry interact",
        f"management {_value(management_socket, 'management socket')} unix",
        "management-client",
        "management-query-passwords",
        "management-hold",
        "ifconfig-noexec",
        "route-noexec",
        "persist-tun",
    ]
    if helper_command:
        command = " ".join(shlex.quote(_value(part, "helper command")) for part in helper_command)
        lines += ["script-security 2", f"route-up {shlex.quote(command)}"]
    lines += [
        f"verb {int(verb)}",
        "key-direction 1",
        "<tls-auth>",
        static_key(server_secret),
        "</tls-auth>",
        "",
    ]
    return "\n".join(lines)


class ManagementSession:
    def __init__(
        self,
        socket_path: str,
        get_token: Callable[[bool], str],
        on_auth_failed: Callable[[], None],
        on_error: Callable[[str], None],
    ) -> None:
        self.socket_path = socket_path
        self._get_token = get_token
        self._on_auth_failed = on_auth_failed
        self._on_error = on_error
        self._conn: socket.socket | None = None
        self._closed = False
        self._failed_once = False
        try:
            os.unlink(socket_path)
        except FileNotFoundError:
            pass
        self._listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        old = os.umask(0o177)
        try:
            self._listener.bind(socket_path)
        finally:
            os.umask(old)
        self._listener.listen(1)

    def run(self) -> None:
        try:
            conn, _ = self._listener.accept()
        except OSError:
            return
        self._listener.close()
        self._conn = conn
        self._send(f"version {CLIENT_VERSION}")
        buffer = b""
        while not self._closed:
            try:
                chunk = conn.recv(4096)
            except OSError:
                break
            if not chunk:
                break
            buffer += chunk
            while b"\n" in buffer:
                raw, buffer = buffer.split(b"\n", 1)
                self._handle(raw.decode("utf-8", "replace").rstrip("\r"))

    def _send(self, line: str) -> None:
        if self._conn:
            self._conn.sendall(line.encode() + b"\n")

    def _handle(self, line: str) -> None:
        if line.startswith(">HOLD:"):
            self._send("hold release")
        elif line.startswith(">PASSWORD:Need 'Auth'"):
            self._send_credentials()
        elif line.startswith(">PASSWORD:Verification Failed"):
            log.warning("the gateway rejected the access token")
            self._on_auth_failed()
        elif line.startswith(">FATAL:"):
            self._on_error(line[len(">FATAL:"):])
        elif line.startswith("ERROR:") and "password" in line.lower():
            log.error("OpenVPN rejected the password; is this the OpenP2S OpenVPN build?")

    def _send_credentials(self) -> None:
        try:
            token = self._get_token(self._failed_once)
        except Exception as error:
            self._on_error(str(error))
            return
        self._send(f'username "Auth" "{AZURE_USERNAME}"')
        self._send('password "Auth"')
        encoded = base64.b64encode(token.encode()).decode()
        for offset in range(0, len(encoded), BASE64_LINE_LENGTH):
            self._send(encoded[offset : offset + BASE64_LINE_LENGTH])
        self._send("END")
        log.info("supplied credentials to OpenVPN")

    def mark_failed(self) -> None:
        self._failed_once = True

    def close(self) -> None:
        self._closed = True
        for sock in (self._conn, self._listener):
            try:
                if sock:
                    sock.close()
            except OSError:
                pass
        try:
            os.unlink(self.socket_path)
        except FileNotFoundError:
            pass
